version: '2'
services:
  data:
    image: tianon/true
    volumes:
      - './volumes/postgresql:/var/lib/postgresql/data'
      - './volumes/media:/usr/local/taiga/media'
      - './volumes/static:/usr/local/taiga/static'
      - './volumes/logs:/usr/local/taiga/logs'
    network_mode: bridge

  db:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_HOST=http://db
    volumes_from:
      - data
    network_mode: bridge

  taigaback:
    build: ./taiga-back
    env_file:
      - .env
    hostname: $HOSTNAME
    environment:
      - SECRET_KEY=$SECRET_KEY
      - EMAIL_USE_TLS=$EMAIL_USE_TLS
      - EMAIL_HOST=$EMAIL_HOST
      - EMAIL_PORT=$EMAIL_PORT
      - EMAIL_HOST_USER=$EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD
      - HOSTNAME=$HOSTNAME
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    links:
      - db
    volumes_from:
      - data
    network_mode: bridge

  taigafront:
    build: ./taiga-front-dist
    env_file:
      - .env
    hostname: $HOSTNAME
    environment: 
      - HOSTNAME=$HOSTNAME
      - VIRTUAL_PORT=$VIRTUAL_PORT
      - VIRTUAL_HOST=$VIRTUAL_HOST
      - LETSENCRYPT_HOST=$LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
    links:
      - taigaback
    volumes_from:
      - data
    network_mode: bridge
